boardRoot/board/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('noticeboard/', include('noticeboard.urls')),
]

boardRoot/noticeboard/urls.py
from django.urls import path
from . import views  # noticeboard의 views를 임포트한다
# URL은 view와 template을 이어주는 역할을 하고, 이 부분을 만들어 주는 작업을
# URLconf라고 한다.path()함수 이용
app_name = 'noticeboard' #일종의 도메인 생성
urlpatterns = [
    path('', views.intro, name='intro'),
    path('covid', views.main, name='covid'),
    path('corona',views.corona, name='corona'),
    path('correlation_tmp',views.correlation_tmp, name='correlation_tmp'),
    path('tmp',views.tmp, name='tmp'),
    path('pm10',views.pm10,name='pm10'),
    path('pm25',views.pm25,name='pm25'),
    path('correlation_dust10',views.correlation_dust10,name='correlation_dust10'),
    path('correlation_dust25',views.correlation_dust25,name='correlation_dust25'),
    path('dust10_yearly',views.dust10_yearly,name='dust10_yearly'),
    path('dust25_yearly',views.dust25_yearly,name='dust25_yearly'),
]

boardRoot/noticeboard/models.py
from django.db import models

# Create your models here.
#models.py에서 테이블을 만든다 클래스타입으로
# 모델은 데이터베이스에 저장되는 데이터를 의미.
# 테이블의 형태로 정리하여 데이터베이스에 넣는다고 생각하면 된다.


    #해당 객체를 출력하면 title이 나오게 한다
#    def __str__(self):
#        return self.title

boardRoot/noticeboard/views.py
from django.shortcuts import render, get_object_or_404
# Create your views here.
# 뷰는 웹(클라이언트) 요청을 받고, 전달받은 데이터들을 해당 어플리케이션의 로직으로 가공하여
# 그 결과를 템플릿에 보내준다. 데이터는 가공하는 처리를 해야한다 싶으면 뷰에서 함수를
# 작성하면 된다.

def intro(request):
    #장고의 ORM 투입!
    #writeDate로 sort해서 가져오기 최신글

    return render(request, 'noticeboard/intro.html')
    #사용자에게 두번째에 있는 html를 세번째에 있는 context를 가져와 rendering해줌

def main(request):
    #장고의 ORM 투입!
    #writeDate로 sort해서 가져오기 최신글

    return render(request, 'noticeboard/main.html')
    #사용자에게 두번째에 있는 html를 세번째에 있는 context를 가져와 rendering해줌


def corona(request):
    #장고의 ORM 투입!
    #writeDate로 sort해서 가져오기 최신글

    return render(request, 'noticeboard/corona.html')
    #사용자에게 두번째에 있는 html를 세번째에 있는 context를 가져와 rendering해줌

def correlation_tmp(request):
    #장고의 ORM 투입!
    #writeDate로 sort해서 가져오기 최신글

    return render(request, 'noticeboard/correlation_tmp.html')
    #사용자에게 두번째에 있는 html를 세번째에 있는 context를 가져와 rendering해줌
# Create your views here.
def tmp(request):
    #장고의 ORM 투입!
    #writeDate로 sort해서 가져오기 최신글

    return render(request, 'noticeboard/tmp.html')
    #사용자에게 두번째에 있는 html를 세번째에 있는 context를 가져와 rendering해줌
def pm10(request):
    #장고의 ORM 투입!
    #writeDate로 sort해서 가져오기 최신글

    return render(request, 'noticeboard/pm10.html')

def pm25(request):
    #장고의 ORM 투입!
    #writeDate로 sort해서 가져오기 최신글

    return render(request, 'noticeboard/pm25.html')

def correlation_dust10(request):
    #장고의 ORM 투입!
    #writeDate로 sort해서 가져오기 최신글

    return render(request, 'noticeboard/correlation_dust10.html')

def correlation_dust25(request):
    #장고의 ORM 투입!
    #writeDate로 sort해서 가져오기 최신글

    return render(request, 'noticeboard/correlation_dust25.html')

def dust10_yearly(request):
    #장고의 ORM 투입!
    #writeDate로 sort해서 가져오기 최신글

    return render(request, 'noticeboard/dust10_yearly.html')

def dust25_yearly(request):
    #장고의 ORM 투입!
    #writeDate로 sort해서 가져오기 최신글

    return render(request, 'noticeboard/dust25_yearly.html')

boardRoot/templates/noticeboard/corona.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>코로나가 먼지!</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Sunflower:wght@300&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Black+And+White+Picture&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Black+And+White+Picture&family=Nanum+Brush+Script&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Black+And+White+Picture&family=Nanum+Brush+Script&family=Nanum+Gothic&display=swap');

body {
  margin: 0;
  padding: 0;
  display: flex;
  flex-flow: column nowrap;
  justify-content: center;
  align-items: center;
  overflow-x: hidden;
}
h1 {
  margin: 2em 0 1.5em 0;
}
header {
}
div_01{
float:right;
}
div_02 {
float:left;
}
nav {
  width: 100%;
  display: flex;
  justify-content: center;
  position: relative;
   background: #B62A51;
  float: right;
}
ul, li {
  margin: 0;
  padding: 0;
  list-style: none;
}
li a.active {
  background-color: #555;
  color: white;
  text-decoration:none;
}
#main-menu > li {
  float: left;
  position: relative;
  font-family: 'Nanum Gothic';
}
#main-menu > li > a {
  font-size: 1.5rem;
  color: rgba(255,255,255,0.85);
  text-align: left;
  text-decoration: none;
  letter-spacing: 0.05em;
  display: block;
  padding: 5px 90px;
  text-shadow: 1px 1px 1px rgba(0,0,0,0.2);
}
#main-menu > li:nth-child(1) > a {
}
#sub-menu {
  position: absolute;
  background: #020202;
  opacity: 0;
  visibility: hidden;
  transition: all 0.15s ease-in;
  font-color: #FDFCFC
}
#sub-menu > li {
  padding: 10px 25px;
  border-bottom: 0px solid rgba(0,0,0,0.15);
}
#sub-menu > li >  a {
  color: rgba(255,255,255,0.6);
  text-decoration: none;
}
#sub-menu > li > hover a{
 text-decoration: none;
   background:#777777;
  font-color: #FEFEFE;
  font-size:0.5em;
}
#main-menu > li:hover #sub-menu {
  opacity: 1;
  visibility: visible;
}
section {
}
     .container { margin: 0; padding: 32px; width: 1024px; }
     .sec { margin-top: 16px; }
     .sec:first-child { margin-top: 0; }
     .title { font-size: 18px; font-weight: 700; }
     .content { margin-top: 8px; }
     .list-box { display: flex; border: 1px solid #aaa; }
     .list-box .list-item { width: 50%; }
     .list-box .list-item:first-child { margin-right: 8px; }
     .list-item dt { padding: 8px 16px; font-weight: 700; color: #888; background-color: #ddd; width: 990px}
     .list-item dd { margin: 0; }
     .list-item iframe { padding: 0 8px; width: 100%; height: 400px; box-sizing: border-box; }
     .list-box2 { display: flex; border: 1px solid #aaa; }
     .list-box2 .list-item:first-child { margin-right: 8px; }
     .list-item dt { padding: 8px 16px; font-weight: 700; color: #888; background-color: #ddd; }
     .list-item dd { margin: 0; }
     .list-item img { padding: 34px; width:168%; }
</style>
</head>
<body bgcolor="#EFDED4">
{% load static %}
<div class="div_01" float="right" ><img src={% static "media/mask.jpg" %} margin-right: 0px; width="900" height="200" ></div>
<header style="left: 0px; width: 450px; bottom: 430px; font-size: 1.8em; font-weight: bold; position: absolute;">
</header>
<nav role="navigation">
  <ul id="main-menu">
<li><a href="{% url 'noticeboard:intro' %}"><b style= font-family:'Sunflower';>코로나가 뭔지</b></a>
    <li><a href="{% url 'noticeboard:pm10' %}">미세먼지</a>
      <ul id="sub-menu">
        <li><a  href="{% url 'noticeboard:pm10' %}" aria-label="subemnu" >미세먼지</a></li>
        <li><a href="{% url 'noticeboard:pm25' %}" aria-label="subemnu">초미세먼지</a></li>
        <li><a href="{% url 'noticeboard:dust10_yearly' %}" aria-label="subemnu">년도별 미세먼지 비교</a></li>
        <li><a href="{% url 'noticeboard:dust25_yearly' %}" aria-label="subemnu">년도별 초미세먼지 비교</a></li>
      </ul>
    </li>
    <li><a href="{% url 'noticeboard:tmp' %}">기온</a>
    </li>
    <li><a href="{% url 'noticeboard:covid' %}">코로나</a>
      <ul id="sub-menu">
        <li><a href="{% url 'noticeboard:corona' %}" aria-label="subemnu">지역,월별 코로나 확진자</a></li>
        <li><a href="{% url 'noticeboard:correlation_dust10' %}" aria-label="subemnu">코로나와 미세먼지의 상관관계</a></li>
        <li><a href="{% url 'noticeboard:correlation_dust25' %}" aria-label="subemnu">코로나와 초미세먼지의 상관관계</a></li>
        <li><a href="{% url 'noticeboard:correlation_tmp' %}" aria-label="subemnu">코로나와 기온의 상관관계</a></li>
      </ul>
    </li>
  </ul>
</nav>
    <main class="container">
        <section class="sec">
            <div class="contents">
                <dl class="list-box">
                    <div class="list-item">
                        <dt>코로나: 지역, 월별 확진자</dt>
                                            <br>&nbsp;&nbsp;&nbsp;<b>지역:</b>&nbsp;&nbsp;&nbsp;<select id="sel", onchange="changeImage()">
        <option value={% static "media/busan.png" %}>부산</option>
        <option value={% static "media/chungbuk.png" %}>충북</option>
        <option value={% static "media/chungnam.png" %}>충남</option>
        <option value={% static "media/daegu.png" %}>대구</option>
        <option value={% static "media/daejeon.png" %}>대전</option>
        <option value={% static "media/gwangju.png" %}>광주</option>
        <option value={% static "media/incheon.png" %}>인천</option>
        <option value={% static "media/jeju.png" %}>제주</option>
        <option value={% static "media/jeonbuk.png" %}>전북</option>
        <option value={% static "media/jeonnam.png" %}>전남</option>
        <option value={% static "media/kangwon.png" %}>강원</option>
        <option value={% static "media/kyoungbuk.png" %}>경북</option>
        <option value={% static "media/kyoungnam.png" %}>경남</option>
        <option value={% static "media/kyounggi.png "%}>경기</option>
        <option value={% static "media/sejong.png" %}>세종</option>
        <option value={% static "media/seoul.png" %}>서울</option>
        <option value={% static "media/ulsan.png" %}>울산</option>
    </select>
<div>
    <p><img id="img" src={% static 'media/busan.png' %} alt="My image"></p>
</div>

            </div>
            </dl>
            </div>
        </section>

    </main>
</div>
    <script>
    function changeImage(){
        let sel=document.querySelector("#sel");
        let img=document.querySelector("#img");
        let index=sel.selectedIndex;
        img.src=sel.options[index].value;
        }
    </script>
</body>
</html>

boardRoot/templates/noticeboard/correlation_dust10.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>코로나가 먼지!</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Sunflower:wght@300&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Black+And+White+Picture&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Black+And+White+Picture&family=Nanum+Brush+Script&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Black+And+White+Picture&family=Nanum+Brush+Script&family=Nanum+Gothic&display=swap');

body {
  margin: 0;
  padding: 0;
  display: flex;
  flex-flow: column nowrap;
  justify-content: center;
  align-items: center;
  overflow-x: hidden;
}
h1 {
  margin: 2em 0 1.5em 0;
}
header {
}
div_01{
float:right;
}
div_02 {
float:left;
}
nav {
  width: 100%;
  display: flex;
  justify-content: center;
  position: relative;
   background: #B62A51;
  float: right;
}
ul, li {
  margin: 0;
  padding: 0;
  list-style: none;
}
li a.active {
  background-color: #555;
  color: white;
  text-decoration:none;
}
#main-menu > li {
  float: left;
  position: relative;
  font-family: 'Nanum Gothic';
}
#main-menu > li > a {
  font-size: 1.5rem;
  color: rgba(255,255,255,0.85);
  text-align: left;
  text-decoration: none;
  letter-spacing: 0.05em;
  display: block;
  padding: 5px 90px;
  text-shadow: 1px 1px 1px rgba(0,0,0,0.2);
}
#main-menu > li:nth-child(1) > a {
}
#sub-menu {
  position: absolute;
  background: #020202;
  opacity: 0;
  visibility: hidden;
  transition: all 0.15s ease-in;
  font-color: #FDFCFC
}
#sub-menu > li {
  padding: 10px 25px;
  border-bottom: 0px solid rgba(0,0,0,0.15);
}
#sub-menu > li >  a {
  color: rgba(255,255,255,0.6);
  text-decoration: none;
}
#sub-menu > li > hover a{
 text-decoration: none;
   background:#777777;
  font-color: #FEFEFE;
  font-size:0.5em;
}
#main-menu > li:hover #sub-menu {
  opacity: 1;
  visibility: visible;
}
section {
}
     .container { margin: 0; padding: 32px; width: 1024px; }
     .sec { margin-top: 16px; }
     .sec:first-child { margin-top: 0; }
     .title { font-size: 18px; font-weight: 700; }
     .content { margin-top: 8px; }
     .list-box { display: flex; border: 1px solid #aaa; }
     .list-box .list-item { width: 50%; }
     .list-box .list-item:first-child { margin-right: 8px; }
     .list-item dt { padding: 8px 16px; font-weight: 700; color: #888; background-color: #ddd; width: 990px}
     .list-item dd { margin: 0; }
     .list-item iframe { padding: 0 8px; width: 100%; height: 400px; box-sizing: border-box; }
     .list-box2 { display: flex; border: 1px solid #aaa; }
     .list-box2 .list-item:first-child { margin-right: 8px; }
     .list-item dt { padding: 8px 16px; font-weight: 700; color: #888; background-color: #ddd; width: 990px }
     .list-item dd { margin: 0; }
     .list-item img { padding: 34px; width:168%; }
</style>
</head>
<body bgcolor="#EFDED4">
{% load static %}
<div class="div_01" float="right" ><img src={% static "media/mask.jpg" %} margin-right: 0px; width="900" height="200" ></div>
<header style="left: 0px; width: 450px; bottom: 430px; font-size: 1.8em; font-weight: bold; position: absolute;">
</header>
<nav role="navigation">
  <ul id="main-menu">
<li><a href="{% url 'noticeboard:intro' %}"><b style= font-family:'Sunflower';>코로나가 뭔지</b></a>
    <li><a href="{% url 'noticeboard:pm10' %}">미세먼지</a>
      <ul id="sub-menu">
        <li><a  href="{% url 'noticeboard:pm10' %}" aria-label="subemnu" >미세먼지</a></li>
        <li><a href="{% url 'noticeboard:pm25' %}" aria-label="subemnu">초미세먼지</a></li>
        <li><a href="{% url 'noticeboard:dust10_yearly' %}" aria-label="subemnu">년도별 미세먼지 비교</a></li>
        <li><a href="{% url 'noticeboard:dust25_yearly' %}" aria-label="subemnu">년도별 초미세먼지 비교</a></li>
      </ul>
    </li>
    <li><a href="{% url 'noticeboard:tmp' %}">기온</a>
    </li>
    <li><a href="{% url 'noticeboard:covid' %}">코로나</a>
      <ul id="sub-menu">
        <li><a href="{% url 'noticeboard:corona' %}" aria-label="subemnu">지역,월별 코로나 확진자</a></li>
        <li><a href="{% url 'noticeboard:correlation_dust10' %}" aria-label="subemnu">코로나와 미세먼지의 상관관계</a></li>
        <li><a href="{% url 'noticeboard:correlation_dust25' %}" aria-label="subemnu">코로나와 초미세먼지의 상관관계</a></li>
        <li><a href="{% url 'noticeboard:correlation_tmp' %}" aria-label="subemnu">코로나와 기온의 상관관계</a></li>
      </ul>
    </li>
  </ul>
</nav>
    <main class="container">
        <section class="sec">
            <div class="contents">
                <dl class="list-box">
                    <div class="list-item">
                        <dt>코로나와 미세먼지의 상관관계</dt>
                                      <br>&nbsp;&nbsp;&nbsp;<b>지역:</b>&nbsp;&nbsp;&nbsp;<select id="sel", onchange="changeImage()">
        <option value={% static "pairplot/pm10/busan.png" %}>부산</option>
        <option value={% static "pairplot/pm10/chungbuk.png" %}>충북</option>
        <option value={% static "pairplot/pm10/chungnam.png" %}>충남</option>
        <option value={% static "pairplot/pm10/daegu.png" %}>대구</option>
        <option value={% static "pairplot/pm10/daejeon.png" %}>대전</option>
        <option value={% static "pairplot/pm10/gwangju.png" %}>광주</option>
        <option value={% static "pairplot/pm10/incheon.png" %}>인천</option>
        <option value={% static "pairplot/pm10/jeju.png" %}>제주</option>
        <option value={% static "pairplot/pm10/jeonbuk.png" %}>전북</option>
        <option value={% static "pairplot/pm10/jeonnam.png" %}>전남</option>
        <option value={% static "pairplot/pm10/kangwon.png" %}>강원</option>
        <option value={% static "pairplot/pm10/kyeongbuk.png" %}>경북</option>
        <option value={% static "pairplot/pm10/kyeongnam.png" %}>경남</option>
        <option value={% static "pairplot/pm10/kyeonggi.png "%}>경기</option>
        <option value={% static "pairplot/pm10/sejong.png" %}>세종</option>
        <option value={% static "pairplot/pm10/seoul.png" %}>서울</option>
        <option value={% static "pairplot/pm10/ulsan.png" %}>울산</option>
    </select>
<div>
    <p><img id="img" src={% static 'pairplot/pm10/busan.png' %} alt="My image"></p>
</div>

            </div>
            </dl>
            </div>
        </section>

    </main>
</div>
    <script>
    function changeImage(){
        let sel=document.querySelector("#sel");
        let img=document.querySelector("#img");
        let index=sel.selectedIndex;
        img.src=sel.options[index].value;
        }
    </script>
</body>
</html>

boardRoot/templates/noticeboard/correlation_dust25.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>코로나가 먼지!</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Sunflower:wght@300&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Black+And+White+Picture&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Black+And+White+Picture&family=Nanum+Brush+Script&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Black+And+White+Picture&family=Nanum+Brush+Script&family=Nanum+Gothic&display=swap');

body {
  margin: 0;
  padding: 0;
  display: flex;
  flex-flow: column nowrap;
  justify-content: center;
  align-items: center;
  overflow-x: hidden;
}
h1 {
  margin: 2em 0 1.5em 0;
}
header {
}
div_01{
float:right;
}
div_02 {
float:left;
}
nav {
  width: 100%;
  display: flex;
  justify-content: center;
  position: relative;
   background: #B62A51;
  float: right;
}
ul, li {
  margin: 0;
  padding: 0;
  list-style: none;
}
li a.active {
  background-color: #555;
  color: white;
  text-decoration:none;
}
#main-menu > li {
  float: left;
  position: relative;
  font-family: 'Nanum Gothic';
}
#main-menu > li > a {
  font-size: 1.5rem;
  color: rgba(255,255,255,0.85);
  text-align: left;
  text-decoration: none;
  letter-spacing: 0.05em;
  display: block;
  padding: 5px 90px;
  text-shadow: 1px 1px 1px rgba(0,0,0,0.2);
}
#main-menu > li:nth-child(1) > a {
}
#sub-menu {
  position: absolute;
  background: #020202;
  opacity: 0;
  visibility: hidden;
  transition: all 0.15s ease-in;
  font-color: #FDFCFC
}
#sub-menu > li {
  padding: 10px 25px;
  border-bottom: 0px solid rgba(0,0,0,0.15);
}
#sub-menu > li >  a {
  color: rgba(255,255,255,0.6);
  text-decoration: none;
}
#sub-menu > li > hover a{
 text-decoration: none;
   background:#777777;
  font-color: #FEFEFE;
  font-size:0.5em;
}
#main-menu > li:hover #sub-menu {
  opacity: 1;
  visibility: visible;
}
section {
}
     .container { margin: 0; padding: 32px; width: 1024px; }
     .sec { margin-top: 16px; }
     .sec:first-child { margin-top: 0; }
     .title { font-size: 18px; font-weight: 700; }
     .content { margin-top: 8px; }
     .list-box { display: flex; border: 1px solid #aaa; }
     .list-box .list-item { width: 50%; }
     .list-box .list-item:first-child { margin-right: 8px; }
     .list-item dt { padding: 8px 16px; font-weight: 700; color: #888; background-color: #ddd; width: 990px}
     .list-item dd { margin: 0; }
     .list-item iframe { padding: 0 8px; width: 100%; height: 400px; box-sizing: border-box; }
     .list-box2 { display: flex; border: 1px solid #aaa; }
     .list-box2 .list-item:first-child { margin-right: 8px; }
     .list-item dt { padding: 8px 16px; font-weight: 700; color: #888; background-color: #ddd; width: 990px }
     .list-item dd { margin: 0; }
     .list-item img { padding: 34px; width:168%;  }
</style>
</head>
<body bgcolor="#EFDED4">
{% load static %}
<div class="div_01" float="right" ><img src={% static "media/mask.jpg" %} margin-right: 0px; width="900" height="200" ></div>
<header style="left: 0px; width: 450px; bottom: 430px; font-size: 1.8em; font-weight: bold; position: absolute;">
</header>
<nav role="navigation">
  <ul id="main-menu">
<li><a href="{% url 'noticeboard:intro' %}"><b style= font-family:'Sunflower';>코로나가 뭔지</b></a>
    <li><a href="{% url 'noticeboard:pm10' %}">미세먼지</a>
      <ul id="sub-menu">
        <li><a  href="{% url 'noticeboard:pm10' %}" aria-label="subemnu" >미세먼지</a></li>
        <li><a href="{% url 'noticeboard:pm25' %}" aria-label="subemnu">초미세먼지</a></li>
        <li><a href="{% url 'noticeboard:dust10_yearly' %}" aria-label="subemnu">년도별 미세먼지 비교</a></li>
        <li><a href="{% url 'noticeboard:dust25_yearly' %}" aria-label="subemnu">년도별 초미세먼지 비교</a></li>
      </ul>
    </li>
    <li><a href="{% url 'noticeboard:tmp' %}">기온</a>
    </li>
    <li><a href="{% url 'noticeboard:covid' %}">코로나</a>
      <ul id="sub-menu">
        <li><a href="{% url 'noticeboard:corona' %}" aria-label="subemnu">지역,월별 코로나 확진자</a></li>
        <li><a href="{% url 'noticeboard:correlation_dust10' %}" aria-label="subemnu">코로나와 미세먼지의 상관관계</a></li>
        <li><a href="{% url 'noticeboard:correlation_dust25' %}" aria-label="subemnu">코로나와 초미세먼지의 상관관계</a></li>
        <li><a href="{% url 'noticeboard:correlation_tmp' %}" aria-label="subemnu">코로나와 기온의 상관관계</a></li>
      </ul>
    </li>
  </ul>
</nav>
    <main class="container">
        <section class="sec">
            <div class="contents">
                <dl class="list-box">
                    <div class="list-item">
                        <dt>코로나와 초미세먼지의 상관관계</dt>
                                <br>&nbsp;&nbsp;&nbsp;<b>지역:</b>&nbsp;&nbsp;&nbsp;<select id="sel", onchange="changeImage()">
        <option value={% static "pairplot/pm25/busan.png" %}>부산</option>
        <option value={% static "pairplot/pm25/chungbuk.png" %}>충북</option>
        <option value={% static "pairplot/pm25/chungnam.png" %}>충남</option>
        <option value={% static "pairplot/pm25/daegu.png" %}>대구</option>
        <option value={% static "pairplot/pm25/daejeon.png" %}>대전</option>
        <option value={% static "pairplot/pm25/gwangju.png" %}>광주</option>
        <option value={% static "pairplot/pm25/incheon.png" %}>인천</option>
        <option value={% static "pairplot/pm25/jeju.png" %}>제주</option>
        <option value={% static "pairplot/pm25/jeonbuk.png" %}>전북</option>
        <option value={% static "pairplot/pm25/jeonnam.png" %}>전남</option>
        <option value={% static "pairplot/pm25/gangwon.png" %}>강원</option>
        <option value={% static "pairplot/pm25/gyeongbuk.png" %}>경북</option>
        <option value={% static "pairplot/pm25/gyeongnam.png" %}>경남</option>
        <option value={% static "pairplot/pm25/gyeonggi.png "%}>경기</option>
        <option value={% static "pairplot/pm25/sejong.png" %}>세종</option>
        <option value={% static "pairplot/pm25/seoul.png" %}>서울</option>
        <option value={% static "pairplot/pm25/ulsan.png" %}>울산</option>
    </select>
    <div>
    <p><img id="img" src={% static 'pairplot/pm25/busan.png' %} alt="My image"></p>
    </div>
            </div>
            </dl>
            </div>
        </section>

    </main>
</div>
    <script>
    function changeImage(){
        let sel=document.querySelector("#sel");
        let img=document.querySelector("#img");
        let index=sel.selectedIndex;
        img.src=sel.options[index].value;
        }
    </script>
</body>
</html>

boardRoot/templates/noticeboard/intro.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>코로나가 먼지!</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Sunflower:wght@300&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Black+And+White+Picture&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Black+And+White+Picture&family=Nanum+Brush+Script&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Black+And+White+Picture&family=Nanum+Brush+Script&family=Nanum+Gothic&display=swap');

    .list-item img {
    width: 1093px;
    display: inline-block;
    margin: 110px;
    float: left;
    margin-top: 30px;
    margin-left: 440px;
    height: 454px;}

    .div_01 img {
    margin: 200px;
    margin-top: -85px;
    margin-left: 534px;
    margin-bottom: 0;
    }

</style>
</head>
<body bgcolor="#EFDED4">
{% load static %}

    <main class="container">
            <div class="contents">
                <dl class="list-box">
                    <div class="list-item">
                        <a href="{% url 'noticeboard:covid' %}" /><img src={% static "main/000picture.jpg" %} />
                    </div>

                </dl>
            </div>
        <div class="div_01" float="right" ><img src={% static "media/mask.jpg" %} margin-right: 0px; width="900" height="200" ></div>

    </main>
</body>
</html>